/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan_modul4;

/**
 *
 * @author Indriawan N
 */
public class Tugas3 extends javax.swing.JFrame { 

    /**
     * Creates new form latihan
     */
    public Tugas3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelktp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        almt = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        kd = new javax.swing.JLabel();
        kec = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        agm = new javax.swing.JLabel();
        sts = new javax.swing.JLabel();
        gd = new javax.swing.JLabel();
        pk = new javax.swing.JLabel();
        kw = new javax.swing.JLabel();
        jtnama = new javax.swing.JTextField();
        jtttl1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtttl2 = new javax.swing.JTextField();
        rblaki = new javax.swing.JRadioButton();
        rbp = new javax.swing.JRadioButton();
        jtalmt = new javax.swing.JTextField();
        jtr1 = new javax.swing.JTextField();
        jtr2 = new javax.swing.JTextField();
        jtkd = new javax.swing.JTextField();
        jtkec = new javax.swing.JTextField();
        jtkota = new javax.swing.JTextField();
        cbagm = new javax.swing.JComboBox<>();
        cbsts = new javax.swing.JComboBox<>();
        cbgd = new javax.swing.JComboBox<>();
        jtpek = new javax.swing.JTextField();
        rbkew1 = new javax.swing.JRadioButton();
        rbkew2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        breset = new javax.swing.JButton();
        bregister = new javax.swing.JButton();
        panelktp2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        ttl2 = new javax.swing.JLabel();
        jk2 = new javax.swing.JLabel();
        almt2 = new javax.swing.JLabel();
        rr2 = new javax.swing.JLabel();
        kd2 = new javax.swing.JLabel();
        kec2 = new javax.swing.JLabel();
        kota2 = new javax.swing.JLabel();
        agm2 = new javax.swing.JLabel();
        sts2 = new javax.swing.JLabel();
        gd2 = new javax.swing.JLabel();
        pk2 = new javax.swing.JLabel();
        kw2 = new javax.swing.JLabel();
        jtnama1 = new javax.swing.JTextField();
        jtttl3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtttl4 = new javax.swing.JTextField();
        jtalmt1 = new javax.swing.JTextField();
        jtr12 = new javax.swing.JTextField();
        jtr22 = new javax.swing.JTextField();
        jtkd2 = new javax.swing.JTextField();
        jtkec2 = new javax.swing.JTextField();
        jtkota2 = new javax.swing.JTextField();
        jtpek2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtkew2 = new javax.swing.JTextField();
        jtgd2 = new javax.swing.JTextField();
        jtagm2 = new javax.swing.JTextField();
        jtsts2 = new javax.swing.JTextField();
        jkk = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu12.setText("jMenu12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new java.awt.CardLayout());

        panelhome.setBackground(new java.awt.Color(0, 204, 153));

        jLabel8.setBackground(new java.awt.Color(0, 204, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indriawan N\\Downloads\\foto-lembuswana-satwa-mitologi-sang-kota-raja.jpg")); // NOI18N

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel8)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel8)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel1.add(panelhome, "card2");

        panelktp.setBackground(new java.awt.Color(255, 255, 0));
        panelktp.setForeground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("FORM KARTU TANDA PENDUDUK");

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setText("Nama");

        ttl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl.setText("Tempat/Tanggal Lahir");

        jk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk.setText("Jenis Kelamin");

        almt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt.setText("Alamat");

        rr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rr.setText("RT/RW");

        kd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd.setText("Kel/Desa");

        kec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec.setText("Kecamatan");

        kota.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota.setText("Kota");

        agm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm.setText("Agama");

        sts.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts.setText("Status");

        gd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd.setText("Golongan Darah");

        pk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk.setText("Pekerjaan");

        kw.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw.setText("Kewarganeraan");

        jLabel15.setText("/");

        rblaki.setText("Laki-Laki");

        rbp.setText("Perempuan");
        rbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpActionPerformed(evt);
            }
        });

        cbagm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Hindu", "Kong Hu Cu" }));

        cbsts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kawin", "Belum Kawin", " " }));

        cbgd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AB", "B", "O" }));

        rbkew1.setText("WNI");

        rbkew2.setText("WNA");

        jLabel16.setText("/");

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bregister.setText("Register");
        bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelktpLayout = new javax.swing.GroupLayout(panelktp);
        panelktp.setLayout(panelktpLayout);
        panelktpLayout.setHorizontalGroup(
            panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelktpLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelktpLayout.createSequentialGroup()
                        .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(ttl)
                            .addComponent(jk)
                            .addComponent(almt)
                            .addGroup(panelktpLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd)
                                    .addComponent(rr)
                                    .addComponent(kec)
                                    .addComponent(kota)))
                            .addComponent(agm)
                            .addComponent(sts)
                            .addComponent(gd)
                            .addComponent(pk)
                            .addComponent(kw))
                        .addGap(26, 26, 26)
                        .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelktpLayout.createSequentialGroup()
                                .addComponent(rbkew1)
                                .addGap(10, 10, 10)
                                .addComponent(rbkew2))
                            .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbsts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbagm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtnama)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(jtttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtttl2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addComponent(jtalmt)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(jtr1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtr2))
                                .addComponent(jtkd)
                                .addComponent(jtkec)
                                .addComponent(jtkota)
                                .addComponent(jtpek)
                                .addGroup(panelktpLayout.createSequentialGroup()
                                    .addComponent(rblaki)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbp)))))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(breset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bregister)
                .addGap(27, 27, 27))
        );
        panelktpLayout.setVerticalGroup(
            panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelktpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(jtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtttl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl)
                        .addComponent(jLabel15)
                        .addComponent(jtttl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk)
                    .addComponent(rblaki)
                    .addComponent(rbp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt)
                    .addComponent(jtalmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr)
                    .addComponent(jtr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd)
                    .addComponent(jtkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec)
                    .addComponent(jtkec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota)
                    .addComponent(jtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm)
                    .addComponent(cbagm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts)
                    .addComponent(cbsts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd)
                    .addComponent(cbgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk)
                    .addComponent(jtpek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw)
                    .addComponent(rbkew1)
                    .addComponent(rbkew2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset)
                    .addComponent(bregister))
                .addGap(24, 24, 24))
        );

        jPanel1.add(panelktp, "card3");

        panelktp2.setBackground(new java.awt.Color(255, 255, 0));
        panelktp2.setForeground(new java.awt.Color(255, 255, 0));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("KARTU TANDA PENDUDUK");

        nama2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama2.setText("Nama");

        ttl2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl2.setText("Tempat/Tanggal Lahir");

        jk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk2.setText("Jenis Kelamin");

        almt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        almt2.setText("Alamat");

        rr2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rr2.setText("RT/RW");

        kd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kd2.setText("Kel/Desa");

        kec2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kec2.setText("Kecamatan");

        kota2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kota2.setText("Kota");

        agm2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        agm2.setText("Agama");

        sts2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sts2.setText("Status");

        gd2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gd2.setText("Golongan Darah");

        pk2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pk2.setText("Pekerjaan");

        kw2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kw2.setText("Kewarganeraan");

        jtnama1.setEditable(false);

        jtttl3.setEditable(false);

        jLabel17.setText("/");

        jtttl4.setEditable(false);

        jtalmt1.setEditable(false);

        jtr12.setEditable(false);

        jtr22.setEditable(false);

        jtkd2.setEditable(false);

        jtkec2.setEditable(false);
        jtkec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtkec2ActionPerformed(evt);
            }
        });

        jtkota2.setEditable(false);

        jtpek2.setEditable(false);

        jLabel18.setText("/");

        jtkew2.setEditable(false);

        jtgd2.setEditable(false);

        jtagm2.setEditable(false);

        jtsts2.setEditable(false);

        jkk.setEditable(false);

        javax.swing.GroupLayout panelktp2Layout = new javax.swing.GroupLayout(panelktp2);
        panelktp2.setLayout(panelktp2Layout);
        panelktp2Layout.setHorizontalGroup(
            panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelktp2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelktp2Layout.createSequentialGroup()
                        .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama2)
                            .addComponent(ttl2)
                            .addComponent(jk2)
                            .addComponent(almt2)
                            .addGroup(panelktp2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd2)
                                    .addComponent(rr2)
                                    .addComponent(kec2)
                                    .addComponent(kota2)))
                            .addComponent(agm2)
                            .addComponent(sts2)
                            .addComponent(gd2)
                            .addComponent(pk2)
                            .addComponent(kw2))
                        .addGap(26, 26, 26)
                        .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtnama1)
                            .addGroup(panelktp2Layout.createSequentialGroup()
                                .addComponent(jtttl3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtttl4, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addComponent(jtalmt1)
                            .addGroup(panelktp2Layout.createSequentialGroup()
                                .addComponent(jtr12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtr22))
                            .addComponent(jtkd2)
                            .addComponent(jtkec2)
                            .addComponent(jtkota2)
                            .addComponent(jtpek2)
                            .addComponent(jtkew2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtgd2)
                            .addComponent(jtagm2)
                            .addComponent(jtsts2)
                            .addComponent(jkk)))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelktp2Layout.setVerticalGroup(
            panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelktp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama2)
                    .addComponent(jtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtttl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttl2)
                        .addComponent(jLabel17)
                        .addComponent(jtttl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jk2)
                    .addComponent(jkk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almt2)
                    .addComponent(jtalmt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rr2)
                    .addComponent(jtr12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtr22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd2)
                    .addComponent(jtkd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kec2)
                    .addComponent(jtkec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kota2)
                    .addComponent(jtkota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agm2)
                    .addComponent(jtagm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sts2)
                    .addComponent(jtsts2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd2)
                    .addComponent(jtgd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pk2)
                    .addComponent(jtpek2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelktp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kw2)
                    .addComponent(jtkew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelktp2, "card4");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));

        jPanel6.setBackground(new java.awt.Color(0, 204, 0));
        jPanel6.setLayout(new java.awt.GridLayout(1, 1, 15, 0));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jButton2.setText("Form KTP ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Indriawan N\\Pictures\\111.png")); // NOI18N
        jLabel1.setText(" ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("KABUPATEN KUTAI KARTANEGARA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("KECAMATAN MARANG KAYU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));

        jLabel5.setText("KABUPATEN KUTAI KARTANEGARA");

        jLabel6.setText("PROVINSI KALIMANTAN TIMUR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel5)
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(jLabel6)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel6)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        jtnama.setText(""); //set untuk mengatur variable exm: jtnama apa bila setTextnya kosong maka nilainya kosong
        jtttl1.setText("");
        jtttl2.setText("");
        buttonGroup1.clearSelection();  //untuk myeleksi panel jenis kelamin
        jtalmt.setText("");
        jtr1.setText("");
        jtr2.setText("");
        jtkd.setText("");
        jtkec.setText("");
        jtkota.setText("");
        cbagm.setSelectedItem(null); //untuk myeleksi panel agama apabila null tidak perlu diisi
        cbsts.setSelectedItem(null); 
        cbgd.setSelectedItem(null);
        jtpek.setText("");
        buttonGroup2.clearSelection();
        
        
    }//GEN-LAST:event_bresetActionPerformed

    private void bregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregisterActionPerformed
        // TODO add your handling code here:
        jtnama1.setText(this.jtnama.getText()); //jtnama1 menggunakan method setText dimana setText itu untuk mengatur dan variable jtnam menggunakan method getText damana getText itu untuk mengambil
        jtttl3.setText(this.jtttl1.getText());
        jtttl4.setText(this.jtttl2.getText());
        if (rblaki.isSelected()) {              //jika laki laki bukan perempuan
            jkk.setText(rblaki.getText());
        }
        else if (rbp.isSelected()) {            //jika tidak perempuan maka laki laki
            jkk.setText(rbp.getText());
        }
        jtalmt1.setText(this.jtalmt.getText());
        jtr12.setText(this.jtr1.getText());
        jtr22.setText(this.jtr2.getText());
        jtkd2.setText(this.jtkd.getText());
        jtkec2.setText(this.jtkec.getText());
        jtkota2.setText(this.jtkota.getText());
        jtagm2.setText(this.cbagm.getSelectedItem().toString()); //agama diberikan nilai menggunakan method setText yang isinya diambil dari cbagm dengan method getSelectitem karena combo box 
        jtsts2.setText(this.cbsts.getSelectedItem().toString());
        jtgd2.setText(this.cbgd.getSelectedItem().toString());
        jtpek2.setText(this.jtpek.getText());
        if (rbkew1.isSelected()) {
            jtkew2.setText(rbkew2.getText());
        }
        else if (rbkew2.isSelected()) {
            jtkew2.setText(rbkew1.getText());
        }
        
        
        
        
        
        /*String Nama, ttl, tl, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan;
        Nama = jtnama.getText();
        ttl = jtttl1.getText();
        tl = jtttl2.getText();
        String JK = null;
        if (rblaki.isSelected())
        {JK = rblaki.getText();}
        else if (rbp.isSelected())
        {JK =rbp.getText();}
        Alamat =jtalmt.getText();
        RT = jtr1.getText();
        RW = jtr2.getText();
        desa = jtkd.getText();
        Kec = jtkec.getText();
        kota = jtkota.getText();
        agama = cbagm.getSelectedItem().toString();
        status = cbsts.getSelectedItem().toString();
        godar = cbgd.getSelectedItem().toString();
        pekerjaan = jtpek.getText();
        String kewarganegaraan=null;
        if (rbkew1.isSelected())
        {kewarganegaraan = rbkew2.getText();}
        else if (rbkew2.isSelected())
        {kewarganegaraan = rbkew1.getText();}

        //panelktp2 x = new panelktp2(Nama, ttl, tl, JK, Alamat, RT, RW, desa, Kec, kota, agama, status, godar, pekerjaan, kewarganegaraan);
        x.setVisible(true);*/
        panelktp2.setVisible(true); //apabila panelktp2 true maka yang muncul panel ktp 
        panelktp.setVisible(false);//apabila panelktp false maka yang muncul panel yang true
    }//GEN-LAST:event_bregisterActionPerformed

    private void jtkec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtkec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtkec2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelhome.setVisible(true);
        panelktp.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelktp.setVisible(true);
        panelhome.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit (0); //untuk mengakhiri program
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agm;
    private javax.swing.JLabel agm2;
    private javax.swing.JLabel almt;
    private javax.swing.JLabel almt2;
    private javax.swing.JButton bregister;
    private javax.swing.JButton breset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbagm;
    private javax.swing.JComboBox<String> cbgd;
    private javax.swing.JComboBox<String> cbsts;
    private javax.swing.JLabel gd;
    private javax.swing.JLabel gd2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel jk2;
    private javax.swing.JTextField jkk;
    private javax.swing.JTextField jtagm2;
    private javax.swing.JTextField jtalmt;
    private javax.swing.JTextField jtalmt1;
    private javax.swing.JTextField jtgd2;
    private javax.swing.JTextField jtkd;
    private javax.swing.JTextField jtkd2;
    private javax.swing.JTextField jtkec;
    private javax.swing.JTextField jtkec2;
    private javax.swing.JTextField jtkew2;
    private javax.swing.JTextField jtkota;
    private javax.swing.JTextField jtkota2;
    private javax.swing.JTextField jtnama;
    private javax.swing.JTextField jtnama1;
    private javax.swing.JTextField jtpek;
    private javax.swing.JTextField jtpek2;
    private javax.swing.JTextField jtr1;
    private javax.swing.JTextField jtr12;
    private javax.swing.JTextField jtr2;
    private javax.swing.JTextField jtr22;
    private javax.swing.JTextField jtsts2;
    private javax.swing.JTextField jtttl1;
    private javax.swing.JTextField jtttl2;
    private javax.swing.JTextField jtttl3;
    private javax.swing.JTextField jtttl4;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel kd2;
    private javax.swing.JLabel kec;
    private javax.swing.JLabel kec2;
    private javax.swing.JLabel kota;
    private javax.swing.JLabel kota2;
    private javax.swing.JLabel kw;
    private javax.swing.JLabel kw2;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama2;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelktp;
    private javax.swing.JPanel panelktp2;
    private javax.swing.JLabel pk;
    private javax.swing.JLabel pk2;
    private javax.swing.JRadioButton rbkew1;
    private javax.swing.JRadioButton rbkew2;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbp;
    private javax.swing.JLabel rr;
    private javax.swing.JLabel rr2;
    private javax.swing.JLabel sts;
    private javax.swing.JLabel sts2;
    private javax.swing.JLabel ttl;
    private javax.swing.JLabel ttl2;
    // End of variables declaration//GEN-END:variables
}
